# Configuration for development environments: unless you are a Tobira
# developer, you are not interested in this file.

[general]
site_title = "Tobira Videoportal"

[db]
password = "tobira"

[log]
level = "trace"

[sync]
host = "localhost:8080"
use_insecure_connection = true
user = "admin"
password = "opencast"
preferred_harvest_size = 3

[theme]
header_height = 36
logo.margin = 1
logo.large.path = "eth-logo.svg"
logo.large.resolution = [192, 31]
logo.small.path = "eth-logo.svg"
logo.small.resolution = [192, 31]

color.navigation = "#1269B0"
color.accent = "#72791C"
color.danger = "#A8322D"
