[general]
site_title = "Tobira Test Deployment"

[db]
database = "tobira-{{ id }}"
user = "tobira-{{ id }}"
password = "tobira-{{ id }}"

[http]
unix_socket = "/opt/tobira/{{ id }}/socket/tobira.sock"
unix_socket_permissions = 0o777

[log]
file = "/var/log/tobira/{{ id }}.log"

[sync]
host = "tobira.ethz.ch"
user = "admin"
password = "{{ opencast_admin_password }}"

[theme]
header_height = 36
logo.margin = 1
logo.large.path = "logo-large.svg"
logo.large.resolution = [192, 31]
logo.small.path = "logo-large.svg"
logo.small.resolution = [192, 31]

color.navigation = "#1269B0"
color.accent = "#72791C"
color.danger = "#A8322D"
